name: fmda
channels:
  - conda-forge
dependencies:
  - python>=3.9.12
  - tensorflow
  - keras
  - pip
  - gdal
  - xarray
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - jupyterlab
  - pip:
    - MesoPy
    - sklearn