name: fmda_ml
channels:
  - conda-forge
dependencies:
  - python>=3.9.12
  - pip
  - tensorflow>=2.9.2
  - keras>=2.9.0
  - matplotlib>=3.5.3
  - numpy
  - pandas
  - jupyter
  - jupyterlab
  - pip:
    - datetime
    - json
    - pickle
    - sklearn

