name: fmda_data
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - gdal
  - cfgrib>=0.9.10.1
  - pygrib
  - pandas
  - metpy
  - numpy
  - xarray>=2022.6.0
  - matplotlib
  - jupyter
  - jupyterlab
  - pip:
    - MesoPy